server:
  port: 8088
  servlet:
    session:
      # 3D
      timeout: PT4320M
spring:
  application:
    name: chatServer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    hikari:
      max-lifetime: 120000
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      in-idle: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
        logic-delete-field: isAvailable
        logic-delete-value: 0
        logic-not-delete-value: 1
